/* -*- mode: C; buffer-read-only: t -*-
   !!!!!!!   DO NOT EDIT THIS FILE   !!!!!!!
   This file is built by regen_perly.pl from perly.y.
   Any changes made here will be lost!
 */

#define PERL_BISON_VERSION  30008

#ifdef PERL_CORE
/* A Bison parser, made by GNU Bison 3.8.2.  */

/* Bison interface for Yacc-like parsers in C

   Copyright (C) 1984, 1989-1990, 2000-2015, 2018-2021 Free Software Foundation,
   Inc.

   This program is free software: you can redistribute it and/or modify
   it under the terms of the GNU General Public License as published by
   the Free Software Foundation, either version 3 of the License, or
   (at your option) any later version.

   This program is distributed in the hope that it will be useful,
   but WITHOUT ANY WARRANTY; without even the implied warranty of
   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
   GNU General Public License for more details.

   You should have received a copy of the GNU General Public License
   along with this program.  If not, see <https://www.gnu.org/licenses/>.  */

/* As a special exception, you may create a larger work that contains
   part or all of the Bison parser skeleton and distribute that work
   under terms of your choice, so long as that work isn't itself a
   parser generator using the skeleton or a modified version thereof
   as a parser skeleton.  Alternatively, if you modify or redistribute
   the parser skeleton itself, you may (at your option) remove this
   special exception, which will cause the skeleton and the resulting
   Bison output files to be licensed under the GNU General Public
   License without this special exception.

   This special exception was added by the Free Software Foundation in
   version 2.2 of Bison.  */

/* DO NOT RELY ON FEATURES THAT ARE NOT DOCUMENTED in the manual,
   especially those whose name start with YY_ or yy_.  They are
   private implementation details that can be changed or removed.  */

/* Debug traces.  */
#ifndef YYDEBUG
# define YYDEBUG 0
#endif
#if YYDEBUG
extern int yydebug;
#endif

/* Token kinds.  */
#ifndef YYTOKENTYPE
# define YYTOKENTYPE
  enum yytokentype
  {
    YYEMPTY = -2,
    YYEOF = 0,                     /* "end of file"  */
    YYerror = 256,                 /* error  */
    YYUNDEF = 257,                 /* "invalid token"  */
    GRAMPROG = 258,                /* GRAMPROG  */
    GRAMEXPR = 259,                /* GRAMEXPR  */
    GRAMBLOCK = 260,               /* GRAMBLOCK  */
    GRAMBARESTMT = 261,            /* GRAMBARESTMT  */
    GRAMFULLSTMT = 262,            /* GRAMFULLSTMT  */
    GRAMSTMTSEQ = 263,             /* GRAMSTMTSEQ  */
    GRAMSUBSIGNATURE = 264,        /* GRAMSUBSIGNATURE  */
    PERLY_AMPERSAND = 265,         /* PERLY_AMPERSAND  */
    PERLY_BRACE_OPEN = 266,        /* PERLY_BRACE_OPEN  */
    PERLY_BRACE_CLOSE = 267,       /* PERLY_BRACE_CLOSE  */
    PERLY_BRACKET_OPEN = 268,      /* PERLY_BRACKET_OPEN  */
    PERLY_BRACKET_CLOSE = 269,     /* PERLY_BRACKET_CLOSE  */
    PERLY_COMMA = 270,             /* PERLY_COMMA  */
    PERLY_DOLLAR = 271,            /* PERLY_DOLLAR  */
    PERLY_DOT = 272,               /* PERLY_DOT  */
    PERLY_EQUAL_SIGN = 273,        /* PERLY_EQUAL_SIGN  */
    PERLY_MINUS = 274,             /* PERLY_MINUS  */
    PERLY_PERCENT_SIGN = 275,      /* PERLY_PERCENT_SIGN  */
    PERLY_PLUS = 276,              /* PERLY_PLUS  */
    PERLY_SEMICOLON = 277,         /* PERLY_SEMICOLON  */
    PERLY_SLASH = 278,             /* PERLY_SLASH  */
    PERLY_SNAIL = 279,             /* PERLY_SNAIL  */
    PERLY_STAR = 280,              /* PERLY_STAR  */
    KW_FORMAT = 281,               /* KW_FORMAT  */
    KW_PACKAGE = 282,              /* KW_PACKAGE  */
    KW_CLASS = 283,                /* KW_CLASS  */
    KW_ROLE = 284,                 /* KW_ROLE  */
    KW_NAMESPACE = 285,            /* KW_NAMESPACE  */
    KW_AS = 286,                   /* KW_AS  */
    KW_LOCAL = 287,                /* KW_LOCAL  */
    KW_MY = 288,                   /* KW_MY  */
    KW_FIELD = 289,                /* KW_FIELD  */
    KW_IF = 290,                   /* KW_IF  */
    KW_ELSE = 291,                 /* KW_ELSE  */
    KW_ELSIF = 292,                /* KW_ELSIF  */
    KW_UNLESS = 293,               /* KW_UNLESS  */
    KW_FOR = 294,                  /* KW_FOR  */
    KW_UNTIL = 295,                /* KW_UNTIL  */
    KW_WHILE = 296,                /* KW_WHILE  */
    KW_CONTINUE = 297,             /* KW_CONTINUE  */
    KW_GIVEN = 298,                /* KW_GIVEN  */
    KW_WHEN = 299,                 /* KW_WHEN  */
    KW_DEFAULT = 300,              /* KW_DEFAULT  */
    KW_CASE = 301,                 /* KW_CASE  */
    KW_MATCH = 302,                /* KW_MATCH  */
    KW_WITH = 303,                 /* KW_WITH  */
    KW_IntVal = 304,               /* KW_IntVal  */
    KW_FloatVal = 305,             /* KW_FloatVal  */
    KW_StrVal = 306,               /* KW_StrVal  */
    KW_TRY = 307,                  /* KW_TRY  */
    KW_CATCH = 308,                /* KW_CATCH  */
    KW_FINALLY = 309,              /* KW_FINALLY  */
    KW_DEFER = 310,                /* KW_DEFER  */
    KW_GEN = 311,                  /* KW_GEN  */
    KW_YIELD = 312,                /* KW_YIELD  */
    KW_REQUIRE = 313,              /* KW_REQUIRE  */
    KW_DO = 314,                   /* KW_DO  */
    KW_USE_or_NO = 315,            /* KW_USE_or_NO  */
    KW_SUB_named = 316,            /* KW_SUB_named  */
    KW_SUB_named_sig = 317,        /* KW_SUB_named_sig  */
    KW_SUB_anon = 318,             /* KW_SUB_anon  */
    KW_SUB_anon_sig = 319,         /* KW_SUB_anon_sig  */
    KW_METHOD_named = 320,         /* KW_METHOD_named  */
    KW_METHOD_anon = 321,          /* KW_METHOD_anon  */
    BAREWORD = 322,                /* BAREWORD  */
    METHCALL0 = 323,               /* METHCALL0  */
    METHCALL = 324,                /* METHCALL  */
    ATTRLIST = 325,                /* ATTRLIST  */
    THING = 326,                   /* THING  */
    PMFUNC = 327,                  /* PMFUNC  */
    PRIVATEREF = 328,              /* PRIVATEREF  */
    QWLIST = 329,                  /* QWLIST  */
    FUNC0OP = 330,                 /* FUNC0OP  */
    FUNC0SUB = 331,                /* FUNC0SUB  */
    UNIOPSUB = 332,                /* UNIOPSUB  */
    LSTOPSUB = 333,                /* LSTOPSUB  */
    PLUGEXPR = 334,                /* PLUGEXPR  */
    PLUGSTMT = 335,                /* PLUGSTMT  */
    LABEL = 336,                   /* LABEL  */
    PROTOTYPE = 337,               /* PROTOTYPE  */
    LOOPEX = 338,                  /* LOOPEX  */
    DOTDOT = 339,                  /* DOTDOT  */
    YADAYADA = 340,                /* YADAYADA  */
    CASE_ELLIPSIS = 341,           /* CASE_ELLIPSIS  */
    FUNC0 = 342,                   /* FUNC0  */
    FUNC1 = 343,                   /* FUNC1  */
    FUNC = 344,                    /* FUNC  */
    UNIOP = 345,                   /* UNIOP  */
    LSTOP = 346,                   /* LSTOP  */
    BLKLSTOP = 347,                /* BLKLSTOP  */
    POWOP = 348,                   /* POWOP  */
    MULOP = 349,                   /* MULOP  */
    ADDOP = 350,                   /* ADDOP  */
    DOLSHARP = 351,                /* DOLSHARP  */
    HASHBRACK = 352,               /* HASHBRACK  */
    NOAMP = 353,                   /* NOAMP  */
    COLONATTR = 354,               /* COLONATTR  */
    FORMLBRACK = 355,              /* FORMLBRACK  */
    FORMRBRACK = 356,              /* FORMRBRACK  */
    SUBLEXSTART = 357,             /* SUBLEXSTART  */
    SUBLEXEND = 358,               /* SUBLEXEND  */
    PHASER = 359,                  /* PHASER  */
    PREC_LOW = 360,                /* PREC_LOW  */
    PLUGIN_LOW_OP = 361,           /* PLUGIN_LOW_OP  */
    OROP = 362,                    /* OROP  */
    PLUGIN_LOGICAL_OR_LOW_OP = 363, /* PLUGIN_LOGICAL_OR_LOW_OP  */
    ANDOP = 364,                   /* ANDOP  */
    PLUGIN_LOGICAL_AND_LOW_OP = 365, /* PLUGIN_LOGICAL_AND_LOW_OP  */
    NOTOP = 366,                   /* NOTOP  */
    ASSIGNOP = 367,                /* ASSIGNOP  */
    PLUGIN_ASSIGN_OP = 368,        /* PLUGIN_ASSIGN_OP  */
    PERLY_QUESTION_MARK = 369,     /* PERLY_QUESTION_MARK  */
    PERLY_COLON = 370,             /* PERLY_COLON  */
    OROR = 371,                    /* OROR  */
    DORDOR = 372,                  /* DORDOR  */
    PLUGIN_LOGICAL_OR_OP = 373,    /* PLUGIN_LOGICAL_OR_OP  */
    ANDAND = 374,                  /* ANDAND  */
    PLUGIN_LOGICAL_AND_OP = 375,   /* PLUGIN_LOGICAL_AND_OP  */
    BITOROP = 376,                 /* BITOROP  */
    BITANDOP = 377,                /* BITANDOP  */
    CHEQOP = 378,                  /* CHEQOP  */
    NCEQOP = 379,                  /* NCEQOP  */
    CHRELOP = 380,                 /* CHRELOP  */
    NCRELOP = 381,                 /* NCRELOP  */
    PLUGIN_REL_OP = 382,           /* PLUGIN_REL_OP  */
    SHIFTOP = 383,                 /* SHIFTOP  */
    PLUGIN_ADD_OP = 384,           /* PLUGIN_ADD_OP  */
    PLUGIN_MUL_OP = 385,           /* PLUGIN_MUL_OP  */
    MATCHOP = 386,                 /* MATCHOP  */
    PERLY_EXCLAMATION_MARK = 387,  /* PERLY_EXCLAMATION_MARK  */
    PERLY_TILDE = 388,             /* PERLY_TILDE  */
    UMINUS = 389,                  /* UMINUS  */
    REFGEN = 390,                  /* REFGEN  */
    PLUGIN_POW_OP = 391,           /* PLUGIN_POW_OP  */
    PREINC = 392,                  /* PREINC  */
    PREDEC = 393,                  /* PREDEC  */
    POSTINC = 394,                 /* POSTINC  */
    POSTDEC = 395,                 /* POSTDEC  */
    POSTJOIN = 396,                /* POSTJOIN  */
    PLUGIN_HIGH_OP = 397,          /* PLUGIN_HIGH_OP  */
    ARROW = 398,                   /* ARROW  */
    PERLY_PAREN_CLOSE = 399,       /* PERLY_PAREN_CLOSE  */
    PERLY_PAREN_OPEN = 400         /* PERLY_PAREN_OPEN  */
  };
  typedef enum yytokentype yytoken_kind_t;
#endif

/* Value type.  */
#ifdef PERL_IN_TOKE_C
static bool
S_is_opval_token(int type) {
    switch (type) {
    case ATTRLIST:
    case BAREWORD:
    case FUNC0OP:
    case FUNC0SUB:
    case LABEL:
    case LSTOPSUB:
    case METHCALL:
    case METHCALL0:
    case PLUGEXPR:
    case PLUGSTMT:
    case PMFUNC:
    case PRIVATEREF:
    case PROTOTYPE:
    case QWLIST:
    case THING:
    case UNIOPSUB:
	return 1;
    }
    return 0;
}
#endif /* PERL_IN_TOKE_C */
#endif /* PERL_CORE */
#if ! defined YYSTYPE && ! defined YYSTYPE_IS_DECLARED
union YYSTYPE
{

    I32	ival; /* __DEFAULT__ (marker for regen_perly.pl;
				must always be 1st union member) */
    void *pval;
    OP *opval;
    GV *gvval;


};
typedef union YYSTYPE YYSTYPE;
# define YYSTYPE_IS_TRIVIAL 1
# define YYSTYPE_IS_DECLARED 1
#endif




int yyparse (void);



/* Generated from:
 * f9ae3d3a0381721e17e78b0df89fe224267df1dfdcd9fdefa60259538b7ed23c perly.y
 * 1a4cfc5b32006b09aba17cc80cd31ade3503ab1e829681adfe337d9c26e19fe0 regen_perly.pl
 * ex: set ro ft=c: */
